### ISSUE TITLE
Workspace error

### ISSUE THREAD

**Issue by 11-check-it-out** [noatpad/obsidian-banners#1]
Workspace of desktop and mobile app got weird after enable the banner plugin. File explorer, tag pane, backlink pane... All were disappeared.![unknown-1.png](https://user-images.githubusercontent.com/47976614/131245886-b6e8da53-2b46-4f01-ad7e-afeae5a5a705.png)

**Comment by noatpad** [comment]
Hm, could be something I use upon the plugin startup to prepare banners for open notes. Can you open up the console, reproduce the issue and show me the log?

**Comment by 11-check-it-out** [comment]
After reproducing, I find that it may more likely change workspace of mobile app. But I can not open the console in mobile app. Therefore, I just show steps to reproduce:

1. Open the banner plugin on desktop app.
2. Sync files to mobile app by Obsidian sync or Syncthing.

Then, workspace of mobile app get weird.

The weird workspace file:

[workspace.zip](https://github.com/noatpad/obsidian-banners/files/7073593/workspace.zip)

**Comment by noatpad** [comment]
So I pushed a different release out that doesn't do the initial workspace load and opts for a different way of doing things, so give it a try to see that fixed it.

https://github.com/noatpad/obsidian-banners/releases/tag/1.1.0

**Comment by noatpad** [comment]
I'm gonna assume that release fixed that problem, but if it comes up again; feel free to reopen!
