### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by albertoloscerritos** [noatpad/obsidian-banners#110]
Hi, this is a great great pluging, but it no longer works with version 1.4.0 and above. Are there plans to update the plugin?
Thanks for your time.

**Comment by ironhak** [comment]
Yes, the plug-in is indeed dead.

**Comment by see7e** [comment]
> Hi, this is a great great pluging, but it no longer works with version 1.4.0 and above. Are there plans to update the plugin? Thanks for your time.

Obsidian version 1.3.7 isn't the last [release](https://github.com/obsidianmd/obsidian-releases/releases)?

**Comment by albertoloscerritos** [comment]
No, the current version is 1.4.3. But it is the catalyst version i.e. you pay 25 USD to get the new versions a little sooner and to support the developers. But indeed, the current public version is 1.3.7. Once you get the 1.4 update, the banner plugin won't work with the new properties view.

**Comment by see7e** [comment]
> No, the current version is 1.4.3. But it is the catalyst version i.e. you pay 25 USD to get the new versions a little sooner and to support the developers. But indeed, the current public version is 1.3.7. Once you get the 1.4 update, the banner plugin won't work with the new properties view.

Oh, there's any clue why it stops working?

**Comment by Zachatoo** [comment]
Already reported in #108, and the plugin author appears to be fixing this

**Comment by noatpad** [comment]
Closing this issue so that discussion can continue to be tracked in #108
