### ISSUE TITLE
Obsidian Update 1.4.5 and clash with your plugin.

### ISSUE THREAD

**Issue by sohan23** [noatpad/obsidian-banners#113]
Things are changing for the **@obsidian**. Despite the high security and highly customizable note-taking app, they are gradually turning their view, and with the recent update, they have implemented **Properties** as a _Notion style_, thus they have locked the **frontmatter**. So now your code doesn't run and the issue is that they are affecting all the notes in a database. 
I hope you see this message and take some action not against it but rather have a workaround so that we can use this beautiful plugin as it is.
you can see the changelog here : https://obsidian.md/changelog/2023-08-31-desktop-v1.4.5/
Thank you.

**Comment by noatpad** [comment]
Also closing this because it's a duplicate of itself (#114), ahah
