### ISSUE TITLE
[Feature Request] Support Notion-style emoji banner

### ISSUE THREAD

**Issue by gylidian** [noatpad/obsidian-banners#12]
Feature description: User can choose an emoji as an icon within banner.

just like this ⬇️

![image](https://user-images.githubusercontent.com/30214981/134315211-3e69db30-c1ed-4032-b705-1d8f86b63c53.png)

---

If welcome this feature, i'll make a pull request. 🎉 

or give me some suggestion

**Comment by noatpad** [comment]
A fellow Notion user, I see. Yeah this one I actually would like to implement down the line, so I'd be down for this. Shouldn't be too hard to implement, though I'm unsure if it should be another YAML field or taken from the first line of text

**Comment by DryIce1** [comment]
Paired with a Notion-like theme and appearance modifications, the Dataview, Metatable and Banners plugins.... it's almost like being on Notion... except it loads super fast and is stored on your own hard drive :)

**Comment by noatpad** [comment]
Heyo! Just put out a release that now includes this as a feature, so there ya go! Hopefully it works well for ya
