### ISSUE TITLE
YAML parsing error causes unopenable file

### ISSUE THREAD

**Issue by YummyOreo** [noatpad/obsidian-banners#120]
If you have a file with invalid frontmatter, like some templates, banners plugin will cause it close.

Repo:
make a file with the following in it
```md
---
test: {}{}
---
```

close it and try and reopen it with banners on

**Comment by noatpad** [comment]
Noted and a fix for it ready on the next beta release. Forgot to add a safeguard around `parseYaml()`, whoops

**Comment by noatpad** [comment]
Should be good to go now in https://github.com/noatpad/obsidian-banners/releases/tag/2.0.1-beta!
