### ISSUE TITLE
Type Mismatch on "banner_header" key

### ISSUE THREAD

**Issue by Aeases** [noatpad/obsidian-banners#121]
The automatic header filename uses a boolean, where as the custom name uses a string, could cause incompatibilities with the upcoming obsidian databases & gives you a ~~ugly~~ (kinda nice looking) warning symbol depending on whether your first banner header was a filename or a custom one. 

![image](https://github.com/noatpad/obsidian-banners/assets/96164686/ff5dc9f6-a964-4d61-9fe7-590cd349c9b4)

One solution could be to just use a word like "filename" to trigger the automatic header, could allow the user to change that in setting too

**Comment by noatpad** [comment]
That's true actually. I forgot about the upcoming database changes would probably require properties to be consistent with their types. For the time being, I think using an empty string could also work to trigger the automatic filename

**Comment by Aeases** [comment]
Yea that sounds like a better solution, great this will be fixed b4 it's out of beta!

**Comment by noatpad** [comment]
All good to go in https://github.com/noatpad/obsidian-banners/releases/tag/2.0.2-beta! An empty (or rather `null`) value will now trigger the auto filename insertion
