### ISSUE TITLE
[Bug] Cannot Insert Text to Canvas Cards with Banner 2.0.1 Beta Enabled

### ISSUE THREAD

**Issue by jr-xing** [noatpad/obsidian-banners#122]
It seems that when the banner v2 beta is enabled, I can no longer add text in the canvas cards. Specifically, I can type in a card, but once I click somewhere else or start a new line, the previously entered text will be completely gone. Banner v1 doesn't cause this problem though.

![banner](https://github.com/noatpad/obsidian-banners/assets/35882478/9736edbc-57b9-4738-a9ee-bcfd59e64d5e)

System info:
```
	Obsidian version: v1.4.13
	Installer version: v1.4.13
	Operating system: Windows 10 Education 10.0.23545
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Obsidian42 - BRAT v0.7.0
		2: Banners v2.0.1-beta
```

**Comment by CrackJackFlood** [comment]
Can confirm

**Comment by noatpad** [comment]
Oh interesting, I guess the canvas cards uses CM6 underneath, so it's trying to do the checks as if it were an editing view pane. Gonna add some safeguards to keep banners out of canvas files in that case

**Comment by noatpad** [comment]
Should be fixed now in https://github.com/noatpad/obsidian-banners/releases/tag/2.0.2-beta!

**Comment by stankovictab** [comment]
This issue is still present in 2.0.5-beta.
