### ISSUE TITLE
Feature Request: Option to adapt banner to readable line length

### ISSUE THREAD

**Issue by cesarpereira904** [noatpad/obsidian-banners#127]
Hi!

I made a few tweaks in the css in order to archive this:
<img width="845" alt="image" src="https://github.com/noatpad/obsidian-banners/assets/70922426/0ba6c137-985b-4a1c-8920-03be781d50f7">

( I'm using AnuPpuccin theme with a background image )

It's working for me but think would be great if there would be an option to match the banner length to the readable line length.

I can share css if needed.

PS: thank you so much for updating this plugin!

**Comment by noatpad** [comment]
Sure! I wasn't sure if there was a use case, but since it can be one, I can add an additional setting to adjust the banner width as well

**Comment by noatpad** [comment]
Available in https://github.com/noatpad/obsidian-banners/releases/tag/2.0.3-beta! Hopefully that should do the trick without a CSS snippet
