### ISSUE TITLE
Does not work with Export to PDF

### ISSUE THREAD

**Issue by Teaguen** [noatpad/obsidian-banners#13]
Hi there, i've been trying to get your plugin to work with Export to PDF but it just ain't playing ball.

Screenshot of what it looks like exporting to PDF: 

![image](https://user-images.githubusercontent.com/46923688/134547046-0789ead7-fc69-42ce-a0f4-135b4340eddf.png)
Versus what it should look like: 
![image](https://user-images.githubusercontent.com/46923688/134547090-92c6c9d1-8dfc-4a67-8e80-38f574183637.png)

Thank you!

**Comment by noatpad** [comment]
Hm, lemme look into this because there's some bug where's it's not positioning the banner correctly

**Comment by phillipsmn** [comment]
I have the same issue. If it helps, I am using the Sanctum theme.

**Comment by noatpad** [comment]
Heyo, pardon the late comeback to this. But I'm gonna put out a release later today that fixes this issue (and if this issue closes, that means I've just merged in the fix)
