### ISSUE TITLE
Can't open lates beta on mobile

### ISSUE THREAD

**Issue by Asetnozama** [noatpad/obsidian-banners#134]
After installing 2.0.4- beta its not possible anymore to activate the plugin on mobile

**Comment by noatpad** [comment]
Ay, didn't realize one of the libraries I used was using the Node API. Will put out a hotfix shortly

**Comment by noatpad** [comment]
Mobile should now start and work properly! https://github.com/noatpad/obsidian-banners/releases/tag/2.0.5-beta

**Comment by QuesadaGrande** [comment]
Thanks a lot!!
