### ISSUE TITLE
Feature Request: Customize the frontmatter field "banner"

### ISSUE THREAD

**Issue by markmarijnissen** [noatpad/obsidian-banners#17]
Add an option to change the frontmatter field "banner".

My current markdown notes (pre-obsidian) have an "image" field, and my website build script uses that one.

**Comment by noatpad** [comment]
Hi there! Pardon the late reply, but I actually went along doing this a bit ago. There's a release coming out later today (and if this issue's closed, that means it's out already) that allows you to change the field, so merci for the request.
