### ISSUE TITLE
Feature Request: Support absolute path 

### ISSUE THREAD

**Issue by markmarijnissen** [noatpad/obsidian-banners#18]
Does not work:
```
banner: /files/201230-dolf-en-mark.png
```

Works
```
banner: files/201230-dolf-en-mark.png
```

I have a website build script that expects  an absolute path (relative to the vault location, see above).  The plugin only works with relative paths, I believe.

Could you add a standardization function, or a function that tries a few locations to find the picture?

**Comment by noatpad** [comment]
This was actually a bug that the path parsing got caught on. I actually changed that part of the code to not only fix this, but also have it function more similarly to internal links if you were to change it. It's also coming in the release later today, so sit tight and merci for catching this
