### ISSUE TITLE
Display Banners in Live Preview

### ISSUE THREAD

**Issue by DryIce1** [noatpad/obsidian-banners#19]
**What**
- If in Preview Mode, Banners are displayed perfectly
- I look forward to seeing Banners also displayed during Live Preview mode. 

**No rush! But thanks for your awesome plugin!**

![image](https://user-images.githubusercontent.com/59501376/142976788-c88f5cf5-f847-4048-a637-a1f59ed229db.png)

**Comment by RyzenFromFire** [comment]
Just found this plugin, this would be a great feature to have.

**Comment by shekhag** [comment]
Love this plugin 💖and looking forward to seeing this in action in live preview mode. Thanks.

**Comment by noatpad** [comment]
Hey there! Pardon the late check on this, but I wanna say that this is like high priority on the roadmap, & I'm currently looking into it _(it's just been a challenge to figure out how CM6 Extensions as a whole personally, ahah)_.

There's a release later coming today that doesn't include this, 'cause I wanted to get through some older issues/suggestions first, but this is being worked on (or rather, being figured out. If anyone has references of other plugins that uses this type of stuff, feel free to throw me any, haha)

**Comment by DryIce1** [comment]
Hi @noatpad, thanks for the update! Unfortunately I haven't got any programming background and haven't ever stepped into the obsidian plugin developer discord channel, so I can't contribute any knowledge here. Best best best of luck!

**Comment by RyzenFromFire** [comment]
I'm using this with a few plugins - specifically Folder Note and Admonitions come to mind. Both of those plugins use codeblocks to generate their features, which I believe would then be passed to Obsidian itself for Live Preview. So I doubt that helps much, but it's what I could think of.

**Comment by Obadiahcruz** [comment]
@noatpad i think nothingislost from discord can help you since he has banners working with codemirroroptions. after you figure how he did it then you can make it work with cm6 for livepreview

**Comment by wismie** [comment]
If I can chime in, I would definitely like to see this working in LP too :)

**Comment by megclaypool** [comment]
I just found this plugin today, and I'm now super excited to see it working in live preview 🙂 Thanks for all your hard work! ❤️

**Comment by nousernameavailableanymore** [comment]
+1 for making this available in live preview

**Comment by noatpad** [comment]
About time I got this working. Should be able to get preliminary support for live preview later today or tomorrow

![about time](https://user-images.githubusercontent.com/21282515/156817479-c69010de-1045-4496-83e2-cf6bf76a48cc.gif)

**Comment by anvimea** [comment]
Awesome, really excited to see banners in live preview. Testament to how great the plugin is that I've been hungering so much for it to work in editing mode!

**Comment by noatpad** [comment]
Preliminary support's up and ready to go! Pardon me that this took _way_ longer than I'd like to admit, ahah.
Go wild, fellas. https://github.com/noatpad/obsidian-banners/releases/tag/1.3.0

**Comment by DryIce1** [comment]
@noatpad thank you so much! It looks great! Even if it did take you longer than you had planned, was it difficult? Would any of the code be relevant for the metatable plugin, because they [might be interested] (https://github.com/arnau/obsidian-metatable/issues/25#issuecomment-1033750276) in any tips and tricks you've learned along the way getting YAML to play with live preview.
Thanks again 👌💪👊

**Comment by megclaypool** [comment]
This is fantastic -- thank you so much for your hard work!!!

**Comment by DryIce1** [comment]
Hi @noatpad, I had a few style problems that I wanted to iron out so the Banners looked nicer, and I think I have good functional solutions for each of them.  Could I ask you to have a quick look at the code below and make sure it's OK? Thanks!

## **Before (problems)**:
- large space before the beginning of the text
- YAML takes up a large amount of space
- The embedded note titles plugin is completely covered over by the banner
![image](https://user-images.githubusercontent.com/59501376/157762995-4760501b-da55-45c7-9074-981239828f2d.png)

## **After (looking good!)**:
![image](https://user-images.githubusercontent.com/59501376/157767464-feb923ae-523e-414f-b9dc-ae1ca089b3f2.png)

## **thoughts and questions**
1. **Remove YAML in live preview** - SOLVED ✔️ see snippet below
1. **Move the beginning of my editable text up** - ✔️ I targetted the banner spacer and turned it off (display: none). Is that OK or is it used for something important?
1. Using the plugin embedded note title, I wanted to **move the embedded note title** to the lower edge of the banner, so that it overlaps with the gradient of the banner. ✔️ - I think it is a neat little calculation, and it looks good. 

## the snippets
``` 
/* ====== Hide YAML in LP ======== */
.is-live-preview .cm-hmd-frontmatter {
    display: none;
}

/* ====== Make the start of the text editor immediately after the banner by not displaying the banner spacer ======== */
.is-live-preview .obsidian-banner-spacer {
    display: none;
}

/* ====== Move the Embedded Note Title down to the lower portion of the banner, overlying the banner faded gradient ======== */
.is-live-preview h1.cm-line.embedded-note-title{
  margin-top: calc(var(--banner-height) - 50px);
}
```

**Comment by DryIce1** [comment]
Unfortunately, the big space came back when I tried inserting icons.
![image](https://user-images.githubusercontent.com/59501376/157770674-22b585b9-ce8f-486b-8c93-751e708a371c.png)
I'll try finding the solution for this later.

**Comment by megclaypool** [comment]
@DryIce1 , how do you edit your YAML frontmatter if it's set to display: none?

**Comment by DryIce1** [comment]
Hi @megclaypool, good question! Snippets Commands plugin to assign hotkey and hide/reveal YAML. I've edited my post above to include this step, thanks.

**Comment by gylidian** [comment]
> Unfortunately, the big space came back when I tried inserting icons. ![image](https://user-images.githubusercontent.com/59501376/157770674-22b585b9-ce8f-486b-8c93-751e708a371c.png) I'll try finding the solution for this later.
> 
> Edit: fixed this with the banner icon adjustment mentioned in above post.

wow, looks so beautiful

**Comment by Issam-seghir** [comment]
I have the same problem here !!

![gif](https://i.imgur.com/fl7TdZ3.gif)
