### ISSUE TITLE
transcluded notes have a vertical offset, despite having no banners

### ISSUE THREAD

**Issue by bnjbvr** [noatpad/obsidian-banners#2]
Hi! Great plugin you made there, thanks a bunch 🤩 !

Just noticed what I _think_ is a small bug: when transcluding a page with the `![Page]` syntax, the embed contains a weird vertical offset that seems to correspond to the banner height, despite the embedded page having no banner. Here's a screenshot:

<img width="1352" alt="Screenshot 2021-08-29 at 20 44 15" src="https://user-images.githubusercontent.com/1180019/131261839-32bd7ce8-9fc7-41d4-8035-51229ab81fa1.png">

The page that embeds ("Home") does have a banner. See vertical space in the `Vrac` embed in this page. I can't reproduce the bug if the embedder page ("Home" here) doesn't have a banner.

Please let me know if you need more info about my setup, and thanks for doing this plugin again 🙏

**Comment by noatpad** [comment]
Oh yeah, I can reproduce this. Basically if a "parent" note has a banner, all of the embedded "children" notes will inherit that vertical spacing rule from the parent. I think I have an easy fix for it too, so I'll get on that.

_I didn't test this with embedded notes either, so I'm glad it's mostly working out of the box too, haha. Maybe I oughta add a setting for that as well_

**Comment by noatpad** [comment]
I was waiting for the plugin to get approved for the community listing, but this should be fixed now in the latest release! Feel free to mention anything else that might be off if you come across something

https://github.com/noatpad/obsidian-banners/releases/tag/1.1.0
