### ISSUE TITLE
Exported Banner

### ISSUE THREAD

**Issue by Rainbell129** [noatpad/obsidian-banners#21]
<img width="409" alt="Screen Shot 2021-12-08 at 3 03 23 PM" src="https://user-images.githubusercontent.com/58488160/145163570-2f4d9c4e-3161-439a-9b67-2dd45a882ff0.png">
<img width="397" alt="Screen Shot 2021-12-08 at 3 03 59 PM" src="https://user-images.githubusercontent.com/58488160/145163624-6e1197ca-d0a6-4da6-ba06-037b04f13a95.png">

When I exported an md file with banner in pdf format it seems to be a bit displaced. Could it be fixed if it's not too much of a trouble?

**Comment by noatpad** [comment]
Hey there! Pardon the late reply to this, ahah. This is the same issue experienced with #13, & I'm just about to push a release to fix this, so sit tight
