### ISSUE TITLE
The algorithm for walking through folders to find images is flawed

### ISSUE THREAD

**Issue by iamfeiyu** [noatpad/obsidian-banners#24]
e.g.1 The file hierarchy is as follows:
- level 1
    - level 12
        - image 1
        - image 2
- level 2
    - image 3

If "Banners Folder "is the default， according to the current algorithm, ”image 3“ cannot be queried.

e.g.2  The file hierarchy is as follows:
- level 1
    - image 3
- level 2
    - level 22
        - image 1
        - image 2

If "Banners Folder "is the default，it can look up all the images.

**Comment by noatpad** [comment]
Yeah it has a bug or two as I discovered. I actually reworked the path parsing a lil' bit and am gonna make a release later today with that change. It should mimic internal links now and that should help with some of that, so hopefully this fixes that
