### ISSUE TITLE
PDF-Export fails

### ISSUE THREAD

**Issue by xNaCly** [noatpad/obsidian-banners#25]
While obsidian-banners is enabled with default settings, obsidian fails to export the selected file to pdf.
Restart or Reinstall didnt help. Disabling obsidian-banners fixed the issue. 
Error in console: 
![image](https://user-images.githubusercontent.com/47723417/148963281-186f5fa0-d579-4258-b6c6-a99c30179834.png)
![image](https://user-images.githubusercontent.com/47723417/148963335-54b12c64-bbb3-4b9f-91f4-d9a3e6463eba.png)

**Comment by Rainbell129** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/58488160/149332668-6a7c7a38-0f4e-4659-b0e8-c7e8c5442f91.png)

**Comment by noatpad** [comment]
Ah, I found a problem. Just a sort of bad check for the "printing" view, I should be able to get a hotfix out real quick. Merci for the catch

**Comment by noatpad** [comment]
Release is out and this should be fixed now!

**Comment by Rainbell129** [comment]
Lovely! Really been enjoying the plug-in!
