### ISSUE TITLE
Can't Export PDF when Plug-in Enabled

### ISSUE THREAD

**Issue by sjensen97219** [noatpad/obsidian-banners#26]
Trying to export a note as a PDF using the built-in Obsidian functionality, I get the following error.

Error: Failed to save PDF.

Also causes generates an error using the Pandoc plugin when trying to export.

Error: Pandoc export failed: TypeError: Cannot read property 'parentElement' of null.

Disabling the Banners plug-in allows exports to work in both cases.  The documents I tried to export have no Banners defined on them.  Export would work on simple notes with no embedded image files.

Obsidian version: 0.13.19 and 0.13.14
Banners version: 1.2.0

Love the plug-in but I have to disabled it for now.  Need the export function more.

Thank you

**Comment by noatpad** [comment]
Hey there, this is pretty much the same thing going on in #25, & it should be fixed with the [1.2.1 release](https://github.com/noatpad/obsidian-banners/releases/tag/1.2.1) that I did yesterday; so can you update the plugin real quick and verify it's all good now?

**Comment by sjensen97219** [comment]
Did the update, now exporting PDF's work with the default Obsidian functionality.  The Pandoc plug-in still has the same error.

BTW, It looks like the version number in the manifest is wrong.

**Comment by noatpad** [comment]
Huh I'll give it a look with Pandoc. I assumed the default PDF export and the Pandoc one worked similarly, but perhaps that's not the case

**Comment by noatpad** [comment]
There should be better handling of a certain check that caused exporting to Pandoc to fail, so feel free to update the newest release to verify it works now

**Comment by sjensen97219** [comment]
It works!  Thank you!  

I exported with Pandoc to PDF and DocX without issues.  The out of the box PDF exports works as well.
