### ISSUE TITLE
REQ: setting to position emoji icons on banner

### ISSUE THREAD

**Issue by janpeeters70** [noatpad/obsidian-banners#27]
I really like your plugin, thanks a lot for developing it. I was wondering if you could add a setting with which you can determine the position of the emoji icon on the banner. Currently it shows like this:

<img width="350" alt="20220118 Obsidian banner emoji 1" src="https://user-images.githubusercontent.com/4502360/149928480-90b04d8b-fb16-40eb-a818-4ee1762c4502.png">

And I would love it like this:

<img width="350" alt="20220118 Obsidian banner emoji 2" src="https://user-images.githubusercontent.com/4502360/149928513-fd254f72-99c0-4f0f-80fe-021a5ad48f98.png">

I know this can be done with custom CSS like:
```
.has-banner-icon .obsidian-banner-icon {
    font-size: 4em;
    margin-top: -.9em; /* originally -1.2em */
    margin-bottom: -0.3em;
}
```
But making it a setting would be great. 
If you want to go all out ;-) you can make it draggable like the banner itself. 
But a disadvantage would probably be another two lines in the frontmatter block for X/Y offset.

Thanks, Jan

**Comment by noatpad** [comment]
A setting is definitely up there in the cards! Right now, I'm a bit experimental with how to position the icons with the banners; so I'll likely adjust their default position a bit better with the next release, & add a bit more customization on where it can be positioned. Making it draggable maaay be a bit tricky, but I'll see what I can do

**Comment by janpeeters70** [comment]
Thanks! Yes making it dragable might be too much anyway. Having a setting would be great.

**Comment by noatpad** [comment]
Heyo, so besides making the icon positioning more consistent, there are now some global customization options to align the icon, as well as the ability to set a custom offset globally.
Individual settings for note is still something I'm gonna tackle later in a bigger scope (I wanna have other settings beside the icon position to be changed via frontmatter fields), but for now, this should be good to position the icon better generally. Feel free to reopen if you have any issues or anything!

**Comment by janpeeters70** [comment]
Hi, thanks for adding these settings. Those are potentially really great but I have some issues though.

- with setting left (h)/center (v) opt half of icon gets chopped off
<img width="154" alt="20220122 Obsidian Banner 2" src="https://user-images.githubusercontent.com/4502360/150642107-3447ae1d-06fe-4560-90c4-11fc731f7ab7.png">

- with custom (v)(e.g. 30px) icons gets chopped off top and bottom.
<img width="188" alt="20220122 Obsidian banner 1" src="https://user-images.githubusercontent.com/4502360/150642083-bbe4cd68-345c-4c12-a54d-6762df973e9e.png">

- with above (v) icon is not visible.

- With below (v) is it visible (this one works)

Do you have an idea what could cause these?

**Comment by noatpad** [comment]
Hm, I'm unsure, 'cause it was working alright with me when I tested it. Can you tell me which theme and/or plugins you have active with this issue? Perhaps also test if it's working properly on the default theme just in case?

**Comment by janpeeters70** [comment]
Hi @noatpad I did some testing. With the default theme everything works fine indeed nevertheless not with Minimal theme.

Maybe you can have a look if this is easily solvable on your end and if not maybe we can contact Kepano the themes' developer.

**Comment by noatpad** [comment]
Hm, I downloaded the Minimal theme on my test vault, but the icon seems to show correctly with the different icon alignments (though it's not exactly aligned with these theme in particular, which might be up to the theme developer or a snippet to fix). I think maybe it might be a plugin you might be using that is altering the styles for it. Can you try disabling plugins and check if there's a plugin that's causing it?

**Comment by janpeeters70** [comment]
It's the [Contextual Typograhy plugin](https://github.com/mgmeyers/obsidian-contextual-typography) that's causing the issues for me. Turning it off shows your banner icons in one piece.

**Comment by janpeeters70** [comment]
Posted it as issue on the developers Github https://github.com/mgmeyers/obsidian-contextual-typography/issues/9

**Comment by noatpad** [comment]
Ohhh okay, I think I found the problem. So it _is_ the Minimal theme, but only when the Contextual Typography plugin is enabled as well, as it has some extra styling rules for it when using that theme.

It's a fairly simple fix, so I just need to make a PR on the Minimal theme repo with those fixes (as well as improve a couple things while I'm at it, like not dimming the banner or the icon, the icon alignment in that particular theme, etc.)

For the time being though, you can use this snippet as a workaround until that PR gets approved and merged in with the theme. Once the theme is updated with that fix, you can disable this snippet afterwards:

```css
.contextual-typography .markdown-preview-view.is-readable-line-width .markdown-preview-sizer>.has-banner-icon {
	overflow: initial;
}
```

**Comment by janpeeters70** [comment]
Hi Danny, great that you found the culprit. Thanks for your research. I'll use the code for you and will watch Minimal themes' repo. I'm following that one too!
