### ISSUE TITLE
Icon displacement on mobile

### ISSUE THREAD

**Issue by Rainbell129** [noatpad/obsidian-banners#28]
Hey dear dev, not sure if it's a bug or not but after the most recent update the position of the icon on my phone (iPhone pro 12) seems to be a bit off.

![image](https://user-images.githubusercontent.com/58488160/149953492-b762bd36-df1d-4554-b201-a4fffa893132.png)

Before the update it was like this

![image](https://user-images.githubusercontent.com/58488160/149954030-458f88a8-6d67-44cb-a69c-68f1e633b3df.png)

But meanwhile I really did update lots of plugins and themes today so I'm not one hundred percent sure it's a banners related problem. Could you check this out if it's not too much trouble?

**Comment by noatpad** [comment]
Hmm, I'll give it a look since I didn't fully test the icons on mobile with this release. If it's a positioning issue, I'll see if I can adjust how it's placed for future releases

**Comment by noatpad** [comment]
The icon position should be better positioned now, both on mobile and on desktop; as well as it having some customization to where you wanna place it. Update to the 1.2.2 release and verify it's all good. Feel free to reopen if there are any more issues regarding this~

**Comment by Rainbell129** [comment]
Bless you! I have tried out the new function and it works really well!

Sent with a Spark<https://sparkmailapp.com/source?from=signature>
