### ISSUE TITLE
gradient option works but i can't call it

### ISSUE THREAD

**Issue by kod4x** [noatpad/obsidian-banners#29]
hi!, i've been trying to set my banner style as gradient, but for some reason it doesn't seem to work, it'll help a lot me if i could get some syntax examples about the property in the documentation, this is an image of all the attempts i made (all of them done separately):

![Obsidian_TpZFU19nQG](https://user-images.githubusercontent.com/58120994/150070446-1901b30e-d2a8-4f62-82d2-554b219377c3.png)

then i gave up and decided to set it as my default value and it worked:

![Obsidian_7wDBO56cfZ](https://user-images.githubusercontent.com/58120994/150071282-08b63e28-f327-4c80-962f-ae167e342da0.png)

i'm not sure if this is a bug of the property or if i needed to do something else.

**Comment by noatpad** [comment]
Oh currently, the plugin only allows you to select the "banner style" at a global level in the settings, so there is no frontmatter field that changes the banner style for a particular note.
Per-note settings is something that I have on the roadmap that will allow you to set the style for individual notes (among other things), but that's still on the backlog for now
