### ISSUE TITLE
Native emoji in icon

### ISSUE THREAD

**Issue by Akimaru666** [noatpad/obsidian-banners#30]
Hi,

The new icon function in really great, but when I tried to add an emoji (🇺🇸), it didn't work as expected and it shows me only a big "U".
<img width="573" alt="Screenshot 2022-01-19 at 19 03 51" src="https://user-images.githubusercontent.com/57895128/150189000-216262c2-2a59-4c8b-9735-96f189d529a3.png">

<img width="573" alt="Screenshot 2022-01-19 at 19 07 19" src="https://user-images.githubusercontent.com/57895128/150189015-b193957b-bad9-4301-a131-dc6fd58ab728.png">

Would it be possible to render native emoji in icon, because those one looks a bit chunky.
Thanks

**Comment by noatpad** [comment]
Huh, so there is an option in the settings that allows you to use the native emojis for your system (`Settings -> Banners -> Use Twemoji`), but disabling that will still produce the incorrect emoji. There might be something off with how I'm parsing emojis, so I'll give it a check
