### ISSUE TITLE
[Feature Request] Add Option to restrict banner dragging

### ISSUE THREAD

**Issue by hiimsergey** [noatpad/obsidian-banners#31]
Dragging a banner can happen accidentally, even by just clicking on it once.
This leads to a new line in the frontmatter being created.
A feature to have this restricted would be very nice.
Thank you.

**Comment by RyzenFromFire** [comment]
I second this.

**Comment by tdwinki** [comment]
An option to restrict banner movement + setting a key combination to move it (e.g. Ctrl + Click to move) would be great.

**Comment by noatpad** [comment]
I can add an option for that, yeah. I'm think of adding an option in the settings to determine a key combination to allow dragging & a "Lock banner position" command for a `banner_lock` YAML field would be a good way to avoid accidental banner movements.

Should be simple enough to implement for the next release

**Comment by noatpad** [comment]
Just pushed out a [release](https://github.com/noatpad/obsidian-banners/releases/tag/1.3.0) for this, and should be ready to go. Now there's a `banner_lock` field that you can toggle using a new command to lock a banner's position if needed, as well as a new setting where you can set a modifier key to be used when dragging banners
