### ISSUE TITLE
[BUG?]. my banner folder is set to / but I am not able to find any images

### ISSUE THREAD

**Issue by cocoonkid** [noatpad/obsidian-banners#33]
[BUG?]. my banner folder is set to / but I am not able to find any images even though I have quite a few in my  designated attachment folder named 0-attachments

How can I debug this or what could this be?

I am on the latest Obsidian version.

**Comment by noatpad** [comment]
Huh, how odd. I can reproduce it and am gonna try fixing it before the next release later today/tomorrow

**Comment by noatpad** [comment]
Yeah there was an error on my part when it came to that. Should be fixed on the [1.3.0](https://github.com/noatpad/obsidian-banners/releases/tag/1.3.0) release, so feel free to reopen if something is still up!

**Comment by cocoonkid** [comment]
@noatpad  My apology for replying that late...

THANKS SO MUCH! Works like a charm now.
