### ISSUE TITLE
Fold / collapse icon for frontmatter missing in LP mode

### ISSUE THREAD

**Issue by nousernameavailableanymore** [noatpad/obsidian-banners#42]
The fold / collapse arrow for YAML frontmatter seems to be missing in LP mode when a banner is set.

Frontmatter can still be collapsed via "Toggle fold on the current line" command.

**Comment by NekoSensei06** [comment]
The arrow seems at the top of the document, we can see it hovering on the frontmatter :
![image](https://user-images.githubusercontent.com/11072451/157009982-78eaee51-43d5-4f7d-9d26-b30cf3186de6.png)

**Comment by nousernameavailableanymore** [comment]
Hmmm, true. I did not see it.
Try finding it in this banner though :D 
![image](https://user-images.githubusercontent.com/45376324/157081035-f5a6e2d4-719d-4ed4-bb5b-3514c4cc6f87.png)

Any way to move it next to the frontmatter dashed lines, where it belongs?

**Comment by DryIce1** [comment]
Hi @nousernameavailableanymore, 
As a non-coder, i opened the Obsidian debugging console for the first time the other day using ` ctrl + shift+ i` and [made these changes to the text position](https://github.com/noatpad/obsidian-banners/issues/19#issuecomment-1064587173).  

You can click on the arrow in the top left of the debugging window. Then you can hover with your mouse, searching for the element in Obsidian. For you, looking for the toggle or the block containing the toggle. 

Then you can write a CSS snippet to move that block from the top margin 200px... or something like that.

**Comment by noatpad** [comment]
Ah yeah, I didn't catch that since the indicator was pretty camouflaged with the images I was testing with, haha. I did some testing and experimenting, & I should be able to put a fix out for the next release

**Comment by noatpad** [comment]
This should be fixed now in the next release now! Do tell if it's all working and feel free to reopen if there's still a problem
https://github.com/noatpad/obsidian-banners/releases/tag/1.3.2

**Comment by MSBack** [comment]
> This should be fixed now in the next release now! Do tell if it's all working and feel free to reopen if there's still a problem https://github.com/noatpad/obsidian-banners/releases/tag/1.3.2

It's not really working for me (not using any snippets for Banners). The indicator is still pretty far off from the yaml, and there is a fairly big gap from the yaml to the banner.
