### ISSUE TITLE
Questions about Emoji

### ISSUE THREAD

**Issue by i-iooi-i** [noatpad/obsidian-banners#43]
Hi
I encountered some problems when using it. It seems that it can't use "Win + . " This key combination adds Emoji. If you can directly add Emoji, I believe it will be more convenient to use.
Thank you for your plug-in. It's really great. 🥰🥰🥰

![动画2](https://user-images.githubusercontent.com/1827701/157366523-c61ee857-75ea-421f-aa5a-c229b8972189.gif)

**Comment by noatpad** [comment]
Ah yeah, that's a nice addition to add to the modal, so I'll get that ready for the next release
