### ISSUE TITLE
Obsidian update destroyed the readable line length full image.

### ISSUE THREAD

**Issue by mmfs37** [noatpad/obsidian-banners#46]
Hi, I had the obs version of a week ago and everything worked as I loved it. Addon is amazing. You can see in the screenshot a snippet of my daily note. Before the update the image was still shows through the complete width. So from total left to total right. That is now in live-preview not anymore the case. The second image is the reading view. That is how I wanted it to be and how it was in the previous version. 
Is it intended to be only line-length at live-preview or is that a "bug" caused by the new version of obsidian.

Will an update patch follow to fix that or is that issue to small/ unimportant?

![image](https://user-images.githubusercontent.com/100991030/160687455-dd959acc-a188-4d3c-9378-a656f90e02d8.png)
![image](https://user-images.githubusercontent.com/100991030/160687780-3253dbd9-7470-4685-b410-dab242e2efd8.png)

**Comment by Obadiahcruz** [comment]
https://github.com/noatpad/obsidian-banners/issues/44#issuecomment-1082463286
