### ISSUE TITLE
Banner re-inserting itself

### ISSUE THREAD

**Issue by ggstrader** [noatpad/obsidian-banners#47]
This only seems to happen with daily notes and I'm not sure why. Whenever I navigate away from the note (whether in edit mode or not), a new YAML block gets inserted before the one already there. This new block only contains the banner and nothing else so it seems like this would be the plugin causing it

![BannerBug](https://user-images.githubusercontent.com/101308963/160952467-bbd1f4b7-311f-4274-b97b-e33a97e47fee.gif)

**Comment by ggstrader** [comment]
Almost forgot to update, I found out the issue was links vs paths.
My daily note template had the banner metadata formatted as embed links: `banner: "![[wallpaper x]]"`
It looks like [this function](https://github.com/noatpad/obsidian-banners/blob/33fdcd03a8f25b3704d57e9d59a6b87e75fb005d/src/main.ts#L237) is where the problem starts, as links are not recognized but full paths are

**Comment by ggstrader** [comment]
Almost forgot to update, I found out the issue was links vs paths.
My daily note template had the banner metadata formatted as embed links: `banner: "![[wallpaper x]]"`
It looks like [this function](https://github.com/noatpad/obsidian-banners/blob/33fdcd03a8f25b3704d57e9d59a6b87e75fb005d/src/main.ts#L237) is where the problem starts, as links are apparently not recognized but full paths are. It looks like it also has an issue if there's any whitespace before the YAML block

**Comment by noatpad** [comment]
Ah yeah, that function was added in there because I changed how the banner "source" field was parsed, & it was gonna pretty much affect everyone. So this patch was gonna discreetly change it to the new format to make things easier, though it looks like it has a bug in it. Does it still happen if you enclose the banner field value in quotes, so something like `banner: value` to `banner: "value"`?

**Comment by noatpad** [comment]
Actually I think I've found the problem and it is the spaces before the frontmatter causing it, so I'll be putting out a fix for that later today with the release

**Comment by noatpad** [comment]
Just put up the release with the fix, so feel free to try it out and see if it's all working for ya!
https://github.com/noatpad/obsidian-banners/releases/tag/1.3.2
