### ISSUE TITLE
TypeError when mixed with the Tasks plugin (interferes with Preview mode processing from Tasks)

### ISSUE THREAD

**Issue by darthmachina** [noatpad/obsidian-banners#5]
When both Tasks and Banners are enabled, there is a TypeError output to the console from Banners and the Preview mode processing of checkbox lists that Tasks performs doesn't work. The error only shows up in the console if both Banners and Tasks are enabled. If I disable Tasks then the error from the Banners code does not appear. This does not prevent Banners from putting the image at the top of Preview, though. I was going to submit a Tasks bug but the error is coming from the Banners code (at least judging by the stack trace below).

There might be issues inter-operating with other plugins but Tasks is the only one that I have that is causing an issue.

```
Uncaught (in promise) TypeError: Cannot read property 'hasClass' of null
    at BannersPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:1542:69)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:31:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:27:12)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:1540:57)
    at Function.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
```

Obsidian Version: 0.12.15
Banners Version: 1.1.0
Tasks Version: 1.3.0

**Comment by noatpad** [comment]
Found the problem. I was basically doing a bad check for parent elements, and the Tasks plugin probably made the needed changes to make that apparent, so this could be apparent with other plugins/scenarios too.

The plugin should only do things with the frontmatter block, so that's fixed now and will be in the next release. Merci for the heads up!
