### ISSUE TITLE
Banner: Mis-alignment

### ISSUE THREAD

**Issue by Missionary2112** [noatpad/obsidian-banners#50]
### Describe the bug
The banner alignment is covering the main text. It just happened recently

**Expected behavior**
The banner should not cover the main text in preview mode

### To Reproduce
1. Install Community Plug-in: Banners 
2. Copy an image link
3. Command palette: Banners: Paste banner from clipboard 
4. See error in Reading mode

### Screenshots

- Reading mode: I have Heading 1 (iOS Apps) & Heading 2 (Owned)
![Screenshot - 2022-04-11 20 42 06 (Obsidian)](https://user-images.githubusercontent.com/98799613/162877660-688cc1b7-701f-4bff-9f7f-0d05961617f8.jpg)

- Preview mode: The Heading 1 is covered by the banner & The Heading 2 is partially covered.
![Screenshot - 2022-04-11 20 40 10 (Obsidian)](https://user-images.githubusercontent.com/98799613/162877670-b8781291-da30-42d9-ac16-274cb38a7e8f.jpg)

- Pop-up window: It's fine with this one.
![Screenshot - 2022-04-11 20 44 47 (Obsidian)](https://user-images.githubusercontent.com/98799613/162877642-4716fd7b-c51f-4cfa-9565-451ad23f40fc.jpg)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v0.14.6

**Comment by noatpad** [comment]
Hmm, does this still happen if you use the default theme? Some themes conflict with how Banners work, so if that's the case, which theme are you using?

**Comment by Missionary2112** [comment]
I'm using ITS theme. And I contacted to ITS theme author and she mentioned the error was due to Breadcrumb plug-in. If I disable Breadcrumb Trail view, the banner is working fine.

**Comment by noatpad** [comment]
Ah yeah, that's been a known plugin that has a conflict with this one. I've been meaning to do some compatibility fixes with plugins like those, but for now, [this can be a workaround](https://github.com/noatpad/obsidian-banners/issues/14#issuecomment-1007829706) that might help your case

**Comment by almogtzabari** [comment]
Any news on that?

**Comment by Missionary2112** [comment]
Oh yeah, it was because of BreadCrumb view that pushes that Banner further down and covers the first few lines. It's fixed now with CSS below, in case you wanna try out. 

```
.obsidian-banner {
	transform: translateY(60px);  /* or whatever amount you need to move it */
}
```

**Comment by almogtzabari** [comment]
**It doesn't really solves my issue because the amount of shift I need  is dynamic.**
In BreadCrumbs, sometimes I have 1 line, and sometimes more (see image below).
Is there a CSS way to make it shift downwards dynamically?
![image](https://user-images.githubusercontent.com/37792505/182574509-3f8bfcea-b1a8-4950-8378-40a968055590.png)

**Comment by Missionary2112** [comment]
As far as I know, you just have to calculate and type in the amount of px to move it, and it would be fixed amount. I don't use many Banners in every of my note so it does not bug me that much.

**Comment by almogtzabari** [comment]
> As far as I know, you just have to calculate and type in the amount of px to move it, and it would be fixed amount. I don't use many Banners in every of my note so it does not bug me that much.

Just to avoid confusion of future readers, I use multiple lines in breadcrumbs, not multiple banners.
In any case, thank you :)
