### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by TfTHacker** [noatpad/obsidian-banners#54]
First off, really like this plugin! thank you for your good work.

I am seeing a lot of errors in the console when moving between files. As a fellow developer, it is well, irritating :-)

They disappear when I turn off Banners plugin.

![image](https://user-images.githubusercontent.com/69121180/164272056-fc58a6cf-e254-4057-9818-1f2d3c6c30af.png)

In advance, thank you.

**Comment by noatpad** [comment]
Oh whoops, I must've forgotten that case; but thankfully it's an easy fix. Lemme push out a hotfix real quick

**Comment by noatpad** [comment]
That should do the trick: https://github.com/noatpad/obsidian-banners/releases/tag/1.3.3

**Comment by TfTHacker** [comment]
Thank you for fixing this.
