### ISSUE TITLE
Bug with Reading Mode

### ISSUE THREAD

**Issue by schobernoise** [noatpad/obsidian-banners#64]
I may have found a bug, is anyone else experiencing this narrowed banner in reading-mode?
![image](https://user-images.githubusercontent.com/58608284/177497866-68d477b6-b0a0-4800-b03f-317f19754d57.png)

I am using Banners 1.3.3 and Obsidian v0.14.15.

I didn't come around yet to test if there is any interference with other plugins.

**Comment by DryIce1** [comment]
I haven't had that problem. 
Does the problem exist in a fresh vault? Or with the default theme? Or with other plugins turned off.
good luck!

**Comment by schobernoise** [comment]
Thanks! So I created a fresh vault, and installed  banners. Everything looks fine. I installed the theme i am using and also no problem. So it gotta be one of the plugins!

**Comment by n6z** [comment]
I was having this issue as well, turning off "copy code block" extension fixed it

**Comment by schobernoise** [comment]
> I was having this issue as well, turning off "copy code block" extension fixed it

I can absolutely confirm this, disabling the extension "Copy Code Block" solved the problem.
