### ISSUE TITLE
Error loading banner image

### ISSUE THREAD

**Issue by kaikuehne** [noatpad/obsidian-banners#9]
Hi Danny,
thanks for this nice plugin!

I'm using Windows 10 and the plugin version `1.1.1`, but I'm getting the following error after I added a banner:

> Error loading banner image! Is the banner field valid?

The file content is this:

```
---
banner: kristaps-ungurs-DoOrFxZ6bMU-unsplash.jpg
---

# Test

Lorem Ipsum ...

![[kristaps-ungurs-DoOrFxZ6bMU-unsplash.jpg]]
```

The inline image is shown fine. Here's a screenshot of how it looks like for me: https://i.imgur.com/pHPxW7f.png
Any idea what is wrong here? Thanks a lot!

**Comment by noatpad** [comment]
Ah, looks like the plugin thinks it's a URL instead of a local image because of the filename. Weird how I didn't catch this earlier because even something like `abc.png` would count as a URL, according to the check I use.

I'll push a quick hotfix release tomorrow when I get the chance!
