### ISSUE TITLE
How can I hide banner in preview pane ?

### ISSUE THREAD

**Issue by Missionary2112** [noatpad/obsidian-banners#95]
I would like to know how can I hide banner in preview window.

In my case, sometimes banners get in the way for me to see the content of a note. It would be great to not see the banner in preview window but it still exists when I open the note.

**Comment by twp248** [comment]
You can toggle off the preview in side the banner plugin. It's called show banner in preview embed.

**Comment by Missionary2112** [comment]
True. I just realize I use Hover Editor plugin and it still appears the banner in preview pane. Thanks! I will contact to author of the plugin.
